spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.brotherjing.serialize.ProtoSerializer
dubbo:
  application:
    name: api
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 3000
    check: false
zookeeper:
  connect-string: localhost:2181
  connection-timeout-ms: 150000
  session-timeout-ms: 600000
  base-sleep-time-ms: 30000
  max-retries: 5
